// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvuoasejunrjsnycysxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dW9hc2VqdW5yanNueWN5c3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTk5NTgsImV4cCI6MjA2NzgzNTk1OH0.CG_tOjvpTv1qDLqstoXwttvsbAZJqEo8gUZ8AeKf1Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});